# GitHub Actions Workflow configuration
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/actions/guides/building-and-testing-nodejs

name: CI

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches-ignore:
    - template
  push:
    branches-ignore:
    - template
  schedule:
  # Run once a week (at 8:50 AM UTC Monday) to check for exogenous breakage.
  # TODO: Run when dependencies are updated.  (Like Dependabot, but on
  # in-range updates and without sending a PR.)
  - cron: '50 8 * * 1'
  workflow_dispatch: {}

jobs:
  test:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        # Note: '*' is "latest LTS version" (without check-latest, it would be
        # "latest LTS version in local cache") because it first checks
        # https://github.com/actions/node-versions/releases then falls back to
        # https://nodejs.org/dist/index.json
        # For explanation and discussion, see:
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version=
        # https://github.com/actions/setup-node/issues/61#issuecomment-577548687
        # https://github.com/actions/setup-node/issues/164#issuecomment-648999618
        # https://github.com/actions/setup-node/pull/104
        #
        # Support for "current"/"latest"/"node" was added in v3.2.0
        # https://github.com/actions/setup-node/pull/483
        node-version: latest
        check-latest: true
    - name: Display Node.js version
      run: node --version
    - name: Install dependencies
      run: npm install --strict-peer-deps
    - name: Validate
      run: npm run validate
