# GitHub Actions Workflow configuration
# https://docs.github.com/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/actions/guides/building-and-testing-nodejs

name: CI

# Note: on key treated as boolean key by YAML
# https://github.com/adrienverge/yamllint/issues/158#issuecomment-454313233
# However, GitHub Actions documentation is consistent in using it unquoted.
on:   # yamllint disable-line rule:truthy
  pull_request:
    branches-ignore:
    - template
  push:
    branches-ignore:
    - template
  schedule:
  # Run once a week (at 8:50 AM UTC Monday) to check for exogenous breakage.
  # TODO: Run when dependencies are updated.  (Like Dependabot, but on
  # in-range updates and without sending a PR.)
  - cron: '50 8 * * 1'
  workflow_dispatch: {}

jobs:
  test:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
    - name: Display Node.js version
      run: node --version
    - name: Install dependencies
      run: npm install --no-strict-peer-deps
    - name: Validate
      run: npm run validate
